[veebiserverid]
web1 ansible_host=192.168.1.50
web2 ansible_host=192.168.1.24

[toodang]
web1

[staging]
web2

[veebiserverid:vars]
ansible_user=it
ansible_python_interpreter=/usr/bin/python3
ansible_password=Pb2026Auth